### ISSUE TITLE
Demo example doesn't work for me

### ISSUE THREAD

**Issue by umaxfun** [osimon8/CombinatorC#4]
I've downloaded `combc-mac`, compiled the example code in the readme into this:

```
0eJztnN1umzAUgO/7FIjLLcmwye+0vcRuqyoiidta4icCUy2q8gB7i13syfYkM5QSAidgjElNtKsmtjEH/J0fn+P09c4wzI0bk31IfWZ+NV55A28iPqOMkoi33KctRtZz6j2s/djbkJAPQaNTn+94hDeZUbyJmMNo4JuF3n0Q0bSN38kwfybXWhNrZJgH/hFPLONYGLwNfJ9sk+FRLlnWhd4meAoJSea6T75kUtFdMuucz7ml4Tam7K0FG0fjwTjmk7x/ym9Y83y4w/ONkejztZHIBiTi03GJfDbeBt6G+g4LwnrRrMksk4x/KkvGwsBdb8iz80KDsPz6H6nLSFikoyxxNjCiT77jvt2SHfapnC80ZDFvHBVeZjps/MMsSpHLEqdkokoP9XckReis41j49nBabjVcTctYoQ5YTYFF3JEt3ZFQeA1RvoaoSlftGmZ3WvNxOwq9jHSdw4ituy5iTiYfNV+tKp3e3gnTJ+WTfDNL3UHM9rGMDIVpjlIYnMuRI1GisASIDQBSBreJKXwmfJFi43wyE0vLCYHcIOcMuOSynFIaMQM0wgkpe/YIo1thpcDSSnG62TX0IiLJTdYF9UCWVeZ/T0InezzzixLtsFRoRxsjmfneKro1k1QceBdLO1fDla0jV5YQV3VUfdbH5tYAUTE/MlQtVFK1UOC/pwPz3+jG/XcFENzoF6GtRu/+GwK5Qc5l//57qcbOznS0s0L+u9Z7q7GzfXtvSANa29mVSju7UkPVXEeqdPHefVNVMT4XqZIyhwjanDTYQySxB0IS+zuE+ze8yFIQiyy0i0VwbSxSNrbnkch3JXqB1EciIdlBGlLFJFWR0QV9aNaA9PL60KNVBrWLCUdQirgtn8ub4vPvr99DIxTe2N8IoVCSXyLKOCXVbX2iDFskyhjXhhmfdIVVNEKQ2NlVotiWO7vLmmQpRReqBkmgi3REVyxAvkLWdNpzhAzB1nrfVaW8E1hQhapTPv4/WD3ZREVgXbJXSClWUJmnbTBoSzPVVzAIAFVb2SmHg3+U0ASGpPvDOi2jrx/DwFtTn0/LL3l03IjoQZ6cS4eobNqMQ55X9WZcUblpqqPZRLeUBlWEXXMkWcWudSh52ecrtc1QUatTCl8jdqdCLn9ZB+9YCbx2zy6/mqaUCiahxKU8WVBxSPiU4OkU3VLdKUFb7TYMqlNIHBNs+4BSRgxL+E58Bd+JoUR265ONhbe50uNoYzU4NDQ72oiU1uwweCbYc1x37DrevimHVqMLtav3Ln/uOa4R2jfVIT4oTIHWs0nDr1CqwuBpakEyaq2kfmSUM6p6kIElipigv1BNBpTHFCUDD4sMrCcZEiXxq9gMKBEpSoY9LDJsPcmQOGAB2hnVZEC5RFEypsMiY6onGVAZtokMyM6oJgPKwomSMRsWGTM9yZA4pAraGdVkQDkuUTLmwyJjricZ0FnkJjIgO6OaDDBHJUjGYlhkLPQkQ2bXCtkZ1WSAyT1BMpbDIqOcANeDDDBZ20TGFX7zYEMZS1EyVsMio/63Px+W6ZLxJpCdaUNG+jc7+2hSRrzkDZz+k0LW4Tobkrx7E02S3PU2eUPHu+M/bo0rjQ==
```

And after import only the second lamp is on, constantly.

![image](https://github.com/osimon8/CombinatorC/assets/521752/57c58aa7-fa8a-46c9-94fc-3e0ecb2778d2)

What am I doing wrong?..

**Comment by osimon8** [comment]
Sorry, this is a little bit confusing - in the demo code, I output the computation part (the top) and the lamp display (bottom) separately, and then manually connected the output to the lamps. If you look closely in the video, the top right substation is wired to the bottom right substation with a green wire. If you do that (and delete the dummy input constant combinator for the lamps on the bottom left), you should get the demo behavior in the video. Technically the bottom right substation is the output pole for the lamps, but since they are just lamps, wiring in the input on that side is equivalent. 

I did this because the circuit placing logic is simplistic, and it's difficult to make the output aesthetically pleasing, so I just had them output separately to make it look nice for the demo video and manually added the one green wire between the right substations to connect them. To have it output a functional circuit directly from the code, instead of the two output statements at the end, you could instead just do `output rate @ ctr @ cmpt @ lamps;`, and that should do what you expect, but it might look like a mess in game.

**Comment by umaxfun** [comment]
Thanks, anyway the project is cool as hell, I've built my first working blueprint in half an hour <3
