### ISSUE TITLE
[question] Can I use medium power poles instead of substations?

### ISSUE THREAD

**Issue by umaxfun** [osimon8/CombinatorC#5]
Can I use medium power poles instead of substations? I didn't research them yet, and [Ultracube](https://mods.factorio.com/mod/Ultracube) requires complex (for my circuit network skills) logic to even produce red circuits :)

I don't know ocaml so I didn't get if it is possible, looking through the code.

**Comment by osimon8** [comment]
It's certainly possible in principle, the reason I have them fixed as substations is because they provide the largest connection range by a wide margin, which simplifies the layout logic by a lot, since otherwise circuits would have to be a lot more compact in order to make sure they are range. I agree that that's definitely not ideal, I'll see if I can come up with a nice way to make it possible to use any type of pole.

As a temporary workaround, you can use [this site](https://factorio.tmin10.ru/) to decode the blueprint string and then  find-replace "substation" with "medium-electric-pole" and re-encode it. That will replace the substations with medium poles in the blueprint, but it might break circuit connections if it is a big circuit and the combinators are too far. You can maybe play around with doing `#LAYOUT NAIVE` as well, or outputting chunks of logic as separate circuits and manually connecting them together in game to mitigate that as well.
